# Generated by Django 5.2.8 on 2025-11-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0003_alter_apartment_options_apartment_bathrooms_and_more'),
        ('residents', '0002_alter_resident_options_alter_vehicle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã hợp đồng')),
                ('contract_type', models.CharField(choices=[('DIRECT', 'Dài hạn - Trực tiếp'), ('INDIRECT', 'Gián tiếp (Môi giới/Sub-lease)'), ('SHORT_TERM', 'Ngắn hạn')], default='DIRECT', max_length=20, verbose_name='Loại hợp đồng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('ACTIVE', 'Đang hiệu lực'), ('EXPIRED', 'Đã hết hạn'), ('TERMINATED', 'Đã thanh lý/Hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='File hợp đồng (PDF/Ảnh)')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tiền đặt cọc (VNĐ)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='buildings.apartment', verbose_name='Căn hộ')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='residents.resident', verbose_name='Người đứng tên')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Danh sách Hợp đồng',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
