# Generated by Django 5.2.8 on 2025-12-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói cước')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã gói')),
                ('bandwidth', models.CharField(max_length=50, verbose_name='Băng thông (VD: 100Mbps)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá cước/tháng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang cung cấp')),
            ],
            options={
                'verbose_name': 'Gói cước Internet',
                'verbose_name_plural': 'Bảng giá Internet',
                'db_table': 'billing_internet_packages',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cấu hình (VD: Giá điện 2025)')),
                ('service_type', models.CharField(choices=[('ELECTRICITY', 'Điện'), ('WATER', 'Nước'), ('MANAGEMENT', 'Phí quản lý')], max_length=20, verbose_name='Loại dịch vụ')),
                ('calculation_method', models.CharField(choices=[('TIERED', 'Bậc thang (Lũy tiến)'), ('FIXED_PER_UNIT', 'Đồng giá theo số tiêu thụ'), ('FIXED_PER_MONTH', 'Cố định theo tháng (Theo căn)'), ('PER_SQM', 'Theo diện tích (VNĐ/m2)')], max_length=20, verbose_name='Cách tính')),
                ('flat_rate', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá cơ bản (VNĐ)')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế VAT (%)')),
                ('environment_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Phí BVMT (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Cấu hình giá dịch vụ',
                'verbose_name_plural': 'Cấu hình giá dịch vụ',
                'db_table': 'billing_service_configs',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại xe')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã loại')),
                ('monthly_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Phí gửi tháng (VNĐ)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loại phương tiện',
                'verbose_name_plural': 'Bảng giá Phương tiện',
                'db_table': 'billing_vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('tier_level', models.IntegerField(verbose_name='Bậc số (1, 2, 3...)')),
                ('min_value', models.IntegerField(verbose_name='Từ số (kWh/m3)')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Đến số (Để trống là vô cùng)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.serviceconfig', verbose_name='Thuộc cấu hình')),
            ],
            options={
                'verbose_name': 'Bậc thang giá',
                'verbose_name_plural': 'Bậc thang giá',
                'db_table': 'billing_price_tiers',
                'ordering': ['tier_level'],
            },
        ),
    ]
