# Generated by Django 5.2.8 on 2025-12-09 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('buildings', '0005_apartment_area_m2_building_units_per_floor_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetier',
            options={'ordering': ['tier_level']},
        ),
        migrations.AlterField(
            model_name='internetpackage',
            name='bandwidth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='internetpackage',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='internetpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internetpackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internetpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.serviceconfig'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='max_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Đến số'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='min_value',
            field=models.IntegerField(verbose_name='Từ số'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='tier_level',
            field=models.IntegerField(verbose_name='Bậc số'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='flat_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá cơ bản'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên cấu hình'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='monthly_price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('service_type', models.CharField(choices=[('ELECTRICITY', 'Điện'), ('WATER', 'Nước')], max_length=20, verbose_name='Loại dịch vụ')),
                ('record_month', models.IntegerField(verbose_name='Tháng')),
                ('record_year', models.IntegerField(verbose_name='Năm')),
                ('old_index', models.IntegerField(default=0, verbose_name='Chỉ số cũ')),
                ('new_index', models.IntegerField(blank=True, null=True, verbose_name='Chỉ số mới')),
                ('consumption', models.IntegerField(default=0, verbose_name='Tiêu thụ')),
                ('image_evidence', models.ImageField(blank=True, null=True, upload_to='meter_readings/%Y/%m/', verbose_name='Ảnh đồng hồ')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ ghi'), ('RECORDED', 'Đã ghi'), ('BILLED', 'Đã tính tiền')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú (Bất thường)')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='buildings.apartment', verbose_name='Căn hộ')),
            ],
            options={
                'verbose_name': 'Chỉ số Điện/Nước',
                'verbose_name_plural': 'Quản lý Chỉ số Điện/Nước',
                'db_table': 'billing_meter_readings',
                'unique_together': {('apartment', 'service_type', 'record_month', 'record_year')},
            },
        ),
    ]
