# Generated by Django 5.2.8 on 2025-12-09 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_pricetier_options_and_more'),
        ('buildings', '0005_apartment_area_m2_building_units_per_floor_default'),
        ('residents', '0003_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã hóa đơn')),
                ('month', models.IntegerField(verbose_name='Kỳ tháng')),
                ('year', models.IntegerField(verbose_name='Kỳ năm')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('OVERDUE', 'Quá hạn'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn thanh toán')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('BANKING', 'Chuyển khoản')], max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='invoices/proofs/%Y/%m/', verbose_name='Ảnh chuyển khoản')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='buildings.apartment', verbose_name='Căn hộ')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident', verbose_name='Chủ hộ')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Quản lý Hóa đơn',
                'db_table': 'billing_invoices',
                'ordering': ['-year', '-month', 'apartment'],
                'unique_together': {('apartment', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('title', models.CharField(max_length=255, verbose_name='Khoản thu')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Diễn giải')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_invoice_items',
            },
        ),
    ]
