# Generated by Django 5.2.8 on 2025-12-10 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=50, verbose_name='Tên ca (VD: Ca Sáng)')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('color_code', models.CharField(default='#3788d8', max_length=7, verbose_name='Màu hiển thị (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình Ca trực',
                'verbose_name_plural': 'Cấu hình Ca trực',
                'db_table': 'operation_shift_configs',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('team', models.CharField(choices=[('SECURITY', 'Tổ Bảo Vệ (An ninh, Bãi xe)'), ('CLEANING', 'Tổ Vệ Sinh (Điện nước, Rác thải)'), ('MAINTENANCE', 'Tổ Kỹ Thuật (Bảo trì)')], max_length=20, verbose_name='Thuộc Tổ/Đội')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang làm việc'), ('ON_LEAVE', 'Đang nghỉ phép'), ('RESIGNED', 'Đã nghỉ việc')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('citizen_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CCCD/CMND')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatars/', verbose_name='Ảnh đại diện')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản hệ thống')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhân viên',
                'verbose_name_plural': 'Quản lý Hồ sơ Nhân viên',
                'db_table': 'operation_staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('date', models.DateField(verbose_name='Ngày trực')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.shiftconfig', verbose_name='Ca trực')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='operation.staffprofile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch phân ca',
                'verbose_name_plural': 'Quản lý Lịch trực',
                'db_table': 'operation_staff_rosters',
                'ordering': ['-date', 'shift__start_time'],
                'unique_together': {('staff', 'shift', 'date')},
            },
        ),
    ]
