# Generated by Django 5.2.8 on 2025-12-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcategory_is_default_and_more'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã công việc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ tiếp nhận'), ('IN_PROGRESS', 'Đang xử lý'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phân công')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='tasks/results/%Y/%m/', verbose_name='Ảnh kết quả')),
                ('staff_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của NV')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_task', to='feedback.feedback', verbose_name='Phản hồi gốc')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operation.staffprofile', verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Công việc bảo trì',
                'verbose_name_plural': 'Quản lý Công việc (Tasks)',
                'db_table': 'operation_maintenance_tasks',
            },
        ),
    ]
