# Generated by Django 5.2.8 on 2025-12-10 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcategory_is_default_and_more'),
        ('operation', '0002_maintenancetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftconfig',
            options={'verbose_name': 'Cấu hình Ca trực', 'verbose_name_plural': 'Cấu hình Ca trực'},
        ),
        migrations.AlterModelOptions(
            name='staffroster',
            options={'verbose_name': 'Lịch phân ca', 'verbose_name_plural': 'Quản lý Lịch trực'},
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterUniqueTogether(
            name='staffroster',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shiftconfig',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='citizen_id',
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_task', to='feedback.feedback'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/results/', verbose_name='Ảnh kết quả'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='staff_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú nhân viên'),
        ),
        migrations.AlterField(
            model_name='shiftconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang áp dụng'),
        ),
        migrations.AlterField(
            model_name='shiftconfig',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên ca trực'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang làm việc'), ('ON_LEAVE', 'Nghỉ phép'), ('RESIGNED', 'Đã nghỉ việc')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='team',
            field=models.CharField(choices=[('SECURITY', 'Tổ Bảo Vệ (An ninh, Bãi xe)'), ('CLEANING', 'Tổ Vệ Sinh (Điện nước, Rác thải)'), ('MAINTENANCE', 'Tổ Kỹ Thuật (Bảo trì)'), ('ADMIN', 'Ban Quản Lý (Văn phòng)')], default='SECURITY', max_length=20, verbose_name='Thuộc Tổ/Đội'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffroster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.shiftconfig'),
        ),
        migrations.AlterField(
            model_name='staffroster',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='operation.staffprofile'),
        ),
        migrations.RemoveField(
            model_name='staffroster',
            name='note',
        ),
    ]
