# Generated by Django 5.2.8 on 2025-11-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('project_name', models.CharField(max_length=255, verbose_name='Tên dự án NOXH')),
                ('logo', models.ImageField(upload_to='landing/logos/', verbose_name='Logo dự án')),
                ('primary_color', models.CharField(default='#1da1f2', max_length=7, verbose_name='Màu chủ đạo (HEX)')),
                ('secondary_color', models.CharField(default='#f70', max_length=7, verbose_name='Màu phụ (HEX)')),
                ('hotline', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(verbose_name='Địa chỉ văn phòng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình Landing Page',
                'verbose_name_plural': 'Cấu hình Landing Page',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('image', models.ImageField(upload_to='landing/hero/', verbose_name='Ảnh Banner (Desktop)')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='landing/hero/', verbose_name='Ảnh Banner (Mobile)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề lớn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('cta_text', models.CharField(default='Đăng ký ngay', max_length=50, verbose_name='Chữ trên nút')),
                ('cta_link', models.CharField(default='#register', max_length=255, verbose_name='Link khi bấm nút')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='landing.landingconfig')),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('question', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('order', models.IntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='landing.landingconfig')),
            ],
            options={
                'verbose_name': 'Hỏi đáp (FAQ)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('icon_class', models.CharField(help_text='VD: fas fa-home (FontAwesome)', max_length=50, verbose_name='Class Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề lợi ích')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('order', models.IntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='landing.landingconfig')),
            ],
            options={
                'verbose_name': 'Lợi ích dự án',
                'ordering': ['order'],
            },
        ),
    ]
