# Generated by Django 5.2.8 on 2025-11-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('step_number', models.CharField(max_length=10, verbose_name='Bước số (VD: 01)')),
                ('title', models.CharField(max_length=100, verbose_name='Tên bước')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('icon_class', models.CharField(help_text='VD: fas fa-file-signature', max_length=50, verbose_name='Icon FontAwesome')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='landing.landingconfig')),
            ],
            options={
                'verbose_name': 'Bước Quy trình',
                'ordering': ['order'],
            },
        ),
    ]
