# Generated by Django 5.2.8 on 2025-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('demand', models.CharField(choices=[('buy', 'Mua ở'), ('invest', 'Đầu tư/Cho thuê')], default='buy', max_length=20, verbose_name='Nhu cầu')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('status', models.CharField(default='new', max_length=20, verbose_name='Trạng thái xử lý')),
            ],
            options={
                'verbose_name': 'Khách hàng đăng ký',
                'verbose_name_plural': 'Danh sách Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tin')),
                ('image', models.ImageField(upload_to='landing/news/', verbose_name='Ảnh đại diện')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Link chi tiết')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='total_apartments',
            field=models.CharField(default='1.200+', max_length=50, verbose_name='Số lượng căn hộ'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='total_blocks',
            field=models.IntegerField(default=5, verbose_name='Số lượng Block'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='total_utilities',
            field=models.CharField(default='100%', max_length=50, verbose_name='Tỷ lệ tiện ích'),
        ),
    ]
