# Generated by Django 5.2.8 on 2025-11-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('identity_card', models.CharField(max_length=20, unique=True, verbose_name='CCCD/CMND')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('identity_card_image_front', models.ImageField(blank=True, null=True, upload_to='residents/id_cards/')),
                ('identity_card_image_back', models.ImageField(blank=True, null=True, upload_to='residents/id_cards/')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT Khẩn cấp')),
                ('relationship_type', models.CharField(choices=[('OWNER', 'Chủ hộ'), ('TENANT', 'Người thuê'), ('MEMBER', 'Thành viên gia đình')], default='TENANT', max_length=20, verbose_name='Vai trò')),
                ('current_apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='buildings.apartment', verbose_name='Căn hộ hiện tại')),
            ],
            options={
                'verbose_name': 'Cư dân',
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(default='Xe máy', max_length=50, verbose_name='Loại xe')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Phương tiện',
                'db_table': 'resident_vehicles',
            },
        ),
    ]
