# Generated by Django 5.2.8 on 2025-11-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Cư dân', 'verbose_name_plural': 'Danh sách Cư dân'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Phương tiện', 'verbose_name_plural': 'Danh sách Phương tiện'},
        ),
    ]
