# Generated by Django 5.2.8 on 2025-12-08 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_options_alter_vehicle_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản hệ thống'),
        ),
    ]
