# Generated by Django 6.0 on 2025-12-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hãng sản xuất'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dòng xe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.resident', verbose_name='Chủ xe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Ô tô'), ('MOTORBIKE', 'Xe máy'), ('BICYCLE', 'Xe đạp'), ('OTHER', 'Khác')], default='MOTORBIKE', max_length=20, verbose_name='Loại xe'),
        ),
    ]
