# Generated by Django 5.2.8 on 2025-11-28 03:14

import apps.feedback.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_apartment_area_m2_building_units_per_floor_default'),
        ('residents', '0002_alter_resident_options_alter_vehicle_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Danh mục phản hồi',
                'verbose_name_plural': 'Danh mục phản hồi',
                'db_table': 'feedback_categories',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Mã phản hồi')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Nội dung chi tiết')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ tiếp nhận'), ('PROCESSING', 'Đang xử lý'), ('DONE', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('source', models.CharField(choices=[('MOBILE', 'Mobile App'), ('WEB', 'Web Portal'), ('DIRECT', 'Trực tiếp/Hotline')], default='MOBILE', max_length=20, verbose_name='Nguồn')),
                ('internal_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ BQL')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='buildings.apartment', verbose_name='Căn hộ')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='residents.resident', verbose_name='Người gửi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='feedback.feedbackcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Phản hồi cư dân',
                'verbose_name_plural': 'Danh sách phản hồi',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('file', models.FileField(upload_to='feedback/%Y/%m/', validators=[apps.feedback.models.validate_file_size], verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại file')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback')),
            ],
            options={
                'db_table': 'feedback_attachments',
            },
        ),
        migrations.CreateModel(
            name='FeedbackStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Chờ tiếp nhận'), ('PROCESSING', 'Đang xử lý'), ('DONE', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Chờ tiếp nhận'), ('PROCESSING', 'Đang xử lý'), ('DONE', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], max_length=20)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thay đổi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='feedback.feedback')),
            ],
            options={
                'db_table': 'feedback_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
