# Generated by Django 5.2.8 on 2025-11-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcategory',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Là mặc định'),
        ),
        migrations.AddField(
            model_name='feedbackcategory',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='Có thể xóa'),
        ),
    ]
