# Generated by Django 6.0 on 2025-12-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcategory_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcategory',
            name='target_team',
            field=models.CharField(choices=[('SECURITY', 'Tổ Bảo Vệ (An ninh, Bãi xe)'), ('CLEANING', 'Tổ Vệ Sinh (Điện nước, Rác thải)'), ('MAINTENANCE', 'Tổ Kỹ Thuật (Bảo trì)'), ('ADMIN', 'Ban Quản Lý (Văn phòng)')], default='MAINTENANCE', max_length=20, verbose_name='Tổ đội phụ trách (Mặc định)'),
        ),
    ]
