# Generated by Django 5.2.8 on 2025-11-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tòa nhà')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('total_floors', models.IntegerField(verbose_name='Tổng số tầng')),
            ],
            options={
                'verbose_name': 'Tòa nhà',
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('floor_number', models.IntegerField(verbose_name='Tầng số')),
                ('apartment_code', models.CharField(max_length=50, unique=True, verbose_name='Mã căn hộ')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích (m2)')),
                ('status', models.CharField(choices=[('VACANT', 'Trống'), ('OCCUPIED', 'Đang ở'), ('MAINTENANCE', 'Bảo trì')], default='VACANT', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả nội thất')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Căn hộ',
                'db_table': 'apartments',
            },
        ),
    ]
