# Generated by Django 5.2.8 on 2025-11-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Căn hộ', 'verbose_name_plural': 'Danh sách Căn hộ'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Tòa nhà', 'verbose_name_plural': 'Danh sách Tòa nhà'},
        ),
    ]
