# Generated by Django 5.2.8 on 2025-11-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_apartment_options_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['building', 'floor_number', 'apartment_code'], 'verbose_name': 'Căn hộ', 'verbose_name_plural': 'Danh sách Căn hộ'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Số nhà vệ sinh'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Số phòng ngủ'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='direction',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hướng nhà'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/apartments/', verbose_name='Hình ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá bán/thuê (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building', verbose_name='Tòa nhà'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Đang mở bán/Trống'), ('OCCUPIED', 'Đã bán/Đang ở'), ('MAINTENANCE', 'Đang bảo trì')], default='VACANT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
