# Generated by Django 5.2.8 on 2025-11-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_apartment_options_apartment_bathrooms_and_more'),
        ('residents', '0002_alter_resident_options_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['building', 'floor_number', 'unit_number'], 'verbose_name': 'Căn hộ', 'verbose_name_plural': 'Danh sách Căn hộ'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='area_m2',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='description',
        ),
        migrations.AddField(
            model_name='apartment',
            name='current_occupant_count',
            field=models.IntegerField(default=0, verbose_name='Số người đang ở'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/floor_plans/', verbose_name='Sơ đồ mặt bằng căn'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả nội thất chi tiết'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_type',
            field=models.CharField(choices=[('RAW', 'Bàn giao thô'), ('BASIC', 'Nội thất cơ bản'), ('FULL', 'Full nội thất')], default='BASIC', max_length=20, verbose_name='Tình trạng nội thất'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='gross_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diện tích tim tường (m2)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='net_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diện tích thông thủy (m2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú BQL'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apartments', to='residents.resident', verbose_name='Chủ sở hữu hiện tại'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('1PN', '1 Phòng ngủ'), ('2PN', '2 Phòng ngủ'), ('3PN', '3 Phòng ngủ'), ('DUPLEX', 'Duplex'), ('PENTHOUSE', 'Penthouse'), ('SHOPHOUSE', 'Shophouse')], default='2PN', max_length=20, verbose_name='Loại phòng'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Số căn (VD: 01)'),
        ),
        migrations.AddField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã tòa nhà'),
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chung'),
        ),
        migrations.AddField(
            model_name='building',
            name='total_units',
            field=models.IntegerField(default=0, verbose_name='Tổng số căn hộ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã căn hộ (Unique)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Số WC'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Số PN'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='direction',
            field=models.CharField(blank=True, choices=[('EAST', 'Đông'), ('WEST', 'Tây'), ('SOUTH', 'Nam'), ('NORTH', 'Bắc'), ('SE', 'Đông Nam'), ('SW', 'Tây Nam'), ('NE', 'Đông Bắc'), ('NW', 'Tây Bắc')], max_length=20, verbose_name='Hướng ban công'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá tham khảo (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Đang mở bán/Trống'), ('OCCUPIED', 'Đã bàn giao/Đang ở'), ('BOOKED', 'Đã đặt cọc'), ('MAINTENANCE', 'Đang bảo trì')], default='VACANT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
