# Generated by Django 5.2.8 on 2025-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_apartment_options_remove_apartment_area_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='units_per_floor_default',
            field=models.IntegerField(default=10, verbose_name='Số căn/tầng mặc định'),
        ),
    ]
