# Generated by Django 5.2.8 on 2025-11-28 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('FEEDBACK_UPDATE', 'Cập nhật phản hồi'), ('SYSTEM', 'Thông báo hệ thống')], default='SYSTEM', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID tham chiếu (VD: Mã FB)')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Đã gửi')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian dự kiến gửi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thực gửi')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách thông báo',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
