# Generated by Django 5.2.8 on 2025-11-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID tham chiếu'),
        ),
    ]
