# Generated by Django 5.2.8 on 2025-11-29 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_read_alter_notification_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('expo_push_token', models.CharField(max_length=255, unique=True, verbose_name='Expo Token')),
                ('platform', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hệ điều hành (ios/android)')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Lần cuối truy cập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thiết bị nhận tin',
                'verbose_name_plural': 'Danh sách thiết bị',
                'db_table': 'notification_devices',
            },
        ),
    ]
