# Generated by Django 5.2.8 on 2025-12-08 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/%Y/%m/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Thông thường'), ('IMPORTANT', 'Quan trọng'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=20, verbose_name='Mức độ ưu tiên'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Định danh đối tượng (VD: Block A)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('ALL_RESIDENTS', 'Toàn bộ cư dân'), ('BLOCK', 'Theo tòa nhà'), ('FLOOR', 'Theo tầng'), ('SPECIFIC_UNITS', 'Danh sách căn hộ cụ thể'), ('INTERNAL_GROUP', 'Nhóm nội bộ (Bảo vệ/Vệ sinh...)'), ('SPECIFIC_USERS', 'Người dùng cụ thể')], default='ALL_RESIDENTS', max_length=50, verbose_name='Loại đối tượng'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('FEEDBACK', 'Phản hồi'), ('ANNOUNCEMENT', 'Thông báo chung'), ('WORK', 'Công việc')], default='SYSTEM', max_length=20, verbose_name='Loại thông báo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID tham chiếu (VD: Mã FB)'),
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification', verbose_name='Thông báo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Người nhận thông báo',
                'verbose_name_plural': 'Danh sách người nhận',
                'db_table': 'notification_recipients',
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_b8c6ee_idx')],
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
